### ISSUE TITLE
Support for 64 bit Integers

### ISSUE THREAD

**Issue by AJHenry** [bkabrda/flask-whooshee#49]
I am trying to use `SQLAlchemy` with BigInteger fields alongside `flask-whooshee`.

It appears when I try to insert a value that is larger than the bounds of a 32-bit integer, it will raise an Exception, specifically `ValueError: Numeric field value 30201746789890 out of range [-2147483648, 2147483647]`.

It is hard to see where this Exception is being raised, however I can see that it is in the `Whoosh.fields` file, [found here](https://github.com/mchaput/whoosh/blob/master/src/whoosh/fields.py#L689)

Any advice on a workaround for this (other than making my BigInteger fields Floats)?

**Comment by AJHenry** [comment]
Here is a full stack trace of the error I receive

```
Traceback (most recent call last):
  File "C:\Users\desktop2\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\desktop2\AppData\Local\Programs\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\desktop2\.virtualenvs\proj-Wy46QQJN\Scripts\flask.exe\__main__.py", line 9, in <module>
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\flask\cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\flask\cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\flask\cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\desktop2\Desktop\proj\index.py", line 842, in save_fetch_command
    save_fetch()
  File "C:\Users\desktop2\Desktop\proj\index.py", line 563, in save_fetch
    db.session.commit()
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\session.py", line 1023, in commit
    self.transaction.commit()
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\session.py", line 487, in commit
    self._prepare_impl()
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\session.py", line 466, in _prepare_impl
    self.session.flush()
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\session.py", line 2446, in flush
    self._flush(objects)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\session.py", line 2584, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\util\langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\util\compat.py", line 277, in reraise
    raise value
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\session.py", line 2544, in _flush
    flush_context.execute()
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 416, in execute
    rec.execute(self)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 583, in execute
    uow,
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\persistence.py", line 264, in save_obj
    ) in states_to_update
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\persistence.py", line 1408, in _finalize_insert_update_commands
    mapper.dispatch.after_insert(mapper, connection, state)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\event\attr.py", line 297, in __call__
    fn(*args, **kw)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\sqlalchemy\orm\events.py", line 637, in wrap
    fn(*arg, **kw)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\flask_whooshee.py", line 425, in after_insert
    self.on_commit([[target, INSERT_KWD]])
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\flask_whooshee.py", line 452, in on_commit
    method(writer, change[0])
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\flask_whooshee.py", line 358, in insert_model
    writer.add_document(**attrs)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\whoosh\writing.py", line 750, in add_document
    for tbytes, freq, weight, vbytes in items:
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\whoosh\fields.py", line 669, in index
    yield (self.to_bytes(num, shift), 1, 1.0, emptybytes)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\whoosh\fields.py", line 722, in to_bytes
    x = self.prepare_number(x)
  File "c:\users\desktop2\.virtualenvs\proj-wy46qqjn\lib\site-packages\whoosh\fields.py", line 692, in prepare_number
    % (x, self.min_value, self.max_value))
ValueError: Numeric field value 301201746789890 out of range [-2147483648, 2147483647]
```

I will look into this later today

**Comment by bkabrda** [comment]
Released in https://pypi.org/project/flask-whooshee/0.7.0/
