### ISSUE TITLE
Throw error when using pagination

### ISSUE THREAD

**Issue by Gurbert** [bkabrda/flask-whooshee#51]
Hi there,

When i'm using the `.whooshee_search()` method alongside the `.paginate()` method in a flask sqlalchemy query the application throw an error. The search can still be performed, the error only happen when I click on the pagination urls.

Here is the code for my flask route:

```
@bp.route('/search/')
def search():
    title = 'Search'
    search_query = request.args.get('q')
    page = request.args.get('page', 1, type=int)
    try:
        posts = Post.query\
            .whooshee_search(search_query, match_substrings=False)\
            .filter_by(published=True)\
            .paginate(page, current_app.config['POSTS_PER_PAGE'], False)
    except ValueError:
        flash('Search string must have at least 3 characters.')
        return redirect(url_for('main.index'))
    next_url = url_for('main.search', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('main.search', page=posts.prev_num) if posts.has_prev else None
    return render_template('index.html', posts=posts.items, title=title, next_url=next_url, prev_url=prev_url)
```

And here is traceback for the error:

```
Traceback (most recent call last):
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "F:\Python\projets\FlaskyPress\app\main\routes.py", line 75, in search
    .whooshee_search(search_query, match_substrings=False)\
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask_whooshee.py", line 93, in whooshee_search
    limit=limit)
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask_whooshee.py", line 156, in search
    prepped_string = cls.prep_search_string(search_string, match_substrings)
  File "F:\Python\projets\FlaskyPress\venv\lib\site-packages\flask_whooshee.py", line 175, in prep_search_string
    s = search_string.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by bkabrda** [comment]
A stupid question: you set `search_query = request.args.get('q')` and then pass that as `search_string`. Is it possible that this happens when the `q` is not set in request args and thus the `get` returns `None`?

**Comment by Gurbert** [comment]
No it was not a stupid question. q was not passed to my pagination links, Thanks for pointing that out now it is working fine.

**Comment by rakeshchandramohan1987** [comment]
Hi,
 I did as you had suggested, from second page onwards it is 404 error. 
 
Please can you help me out
